language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-23.0.1
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
    - cd PONG
    - gradle -b wrapper.gradle wrapper
